services:
  db:
    image: mongo
    container_name: db
    restart: always
    command: --dbpath /data/db
    networks:
      - node-network

  backend:
    build:
      context: backend
    container_name: backend
    tty: true
    working_dir: /app
    command: npm run start-containerized
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8090
      MONGO_DB_CNN_STRING: mongodb://db:27017
    networks:
      - node-network
    ports:
      - '8090:8090'
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    container_name: frontend
    working_dir: /app
    networks:
      - node-network
    ports:
      - '5173:5173'
    environment:
      VITE_API_PORT: 8090
    command: npm run host
    depends_on:
      - backend

networks:
  node-network:
    driver: bridge
